# Generated by Django 5.1.2 on 2024-10-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_creativereser_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='peer1reser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_idpeer1', models.IntegerField()),
                ('namepeer1', models.CharField(max_length=100)),
                ('event_datepeer1', models.DateField()),
                ('start_timepeer1', models.TimeField(blank=True, null=True)),
                ('end_timepeer1', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
