# Generated by Django 5.1.2 on 2024-10-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_peer1reser'),
    ]

    operations = [
        migrations.CreateModel(
            name='peer2reser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_idpeer2', models.IntegerField()),
                ('namepeer2', models.CharField(max_length=100)),
                ('event_datepeer2', models.DateField()),
                ('start_timepeer2', models.TimeField(blank=True, null=True)),
                ('end_timepeer2', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
