# Generated by Django 5.1.2 on 2024-10-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_peerone'),
        ('mypage', '0005_peer2reser'),
    ]

    operations = [
    ]
