# Generated by Django 5.1.2 on 2024-10-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0006_merge_0002_peerone_0005_peer2reser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='peerone',
        ),
    ]
